# Generated by Django 6.0.3 on 2026-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='merch_images/', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Например: Материал: 100% хлопок', verbose_name='Характеристики'),
        ),
    ]
