# Generated by Django 6.0.3 on 2026-04-06 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_date_of_birth_employee_is_intern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время прохода')),
                ('is_entry', models.BooleanField(default=True, verbose_name='Вход')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проход через проходную',
                'verbose_name_plural': 'Логи проходной',
            },
        ),
    ]
