# Generated by Django 6.0.3 on 2026-04-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_intern',
            field=models.BooleanField(default=False, verbose_name='Стажёр'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to=settings.AUTH_USER_MODEL, verbose_name='Ментор'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_bonus_received',
            field=models.BooleanField(default=False, verbose_name='Бонус за заполнение профиля получен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trial_passed',
            field=models.BooleanField(default=False, verbose_name='Стажировка пройдена'),
        ),
    ]
