# Generated by Django 6.0.3 on 2026-04-06 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_checkin_employee_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц плана')),
                ('target_tasks', models.PositiveIntegerField(verbose_name='Цель (кол-во задач/деталей)')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('is_rewarded', models.BooleanField(default=False, verbose_name='Бонус начислен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'План работ',
                'verbose_name_plural': 'Планы работ',
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
