# Generated by Django 6.0.3 on 2026-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='needs_password_change',
            field=models.BooleanField(default=True, verbose_name='Требуется смена пароля'),
        ),
    ]
