# Generated by Django 6.0.3 on 2026-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название заслуги')),
                ('code', models.SlugField(help_text="Например: 'birthday' или 'punctuality'", unique=True, verbose_name='Технический код')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма вознаграждения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Настройка вознаграждения',
                'verbose_name_plural': 'Настройки вознаграждений',
            },
        ),
        migrations.DeleteModel(
            name='RewardRule',
        ),
    ]
