# Generated by Django 6.0.3 on 2026-04-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_rewardsetting_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardSetting',
        ),
    ]
